# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu_16"
  
  config.vm.define "webtest01" do |webtest01|
  
    webtest01.vm.hostname = "webtest01"
	
    webtest01.vm.network "private_network", ip: "192.168.5.3"

  end
  
end