# -*- mode: ruby -*-
# vi: set ft=ruby :


VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu_16"

  config.vm.define "web01" do |web01|
  
    web01.vm.hostname = "web01"
  
    web01.vm.network "private_network", ip: "192.168.5.11"
  
  end
  
end