# -*- mode: ruby -*-
# vi: set ft=ruby :


VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu_16"

  config.vm.define "puppetmaster" do |puppetmaster|
  
    puppetmaster.vm.hostname = "puppetmaster"
  
    puppetmaster.vm.network "private_network", ip: "192.168.5.1"
  
  end
  
end